ライトのオンオフ機能の追加
IoA-project/LightingSimulation pull request #1
Opened 2020-11-13 01:47 UTC by chicchi8

## 画面に表示するボタンの追加
## ライトのオンオフのスクリプト
## ライトのプレハブ化

2020-11-14 04:39 UTC, rainierrr commented
実装ありがとう！
いくつか修正してほしい点があるのでお願いします。

### 修正点
#### 配置について
プレハブやスクリプトがどのシーンで作成されたものなのかがわかりにくいので変更してほしいです。
プレハブであれば  ` Asset/Prefabs/シーン名/`
スクリプトであれば   `Asset/Scripts/シーン名/`
みないな位置に配置して下さい。

#### PointLightオブジェクトについて
LightingSimulationSenceにPointLightオブジェクトがたくさんあるけど一個でいいかも。
なにか意図があれば連絡下さい。

#### プレハブ化
基本的にSenceに置くものはすべてプレハブ化の方向にしようと思ってます。
そのため一応ですがCanvasもプレハブ化をお願いします。

#### その他
スクリプトについては別途書きます。
EventSystemがなにをやっているのかわからなかったので教えてほしいです。

2020-11-14 04:56 UTC, rainierrr requested changes
みすって一PR Closeしちゃいました。すいません。

2020-11-14 05:00 UTC, rainierrr commented
> 現状すべてのLightコンポートネントを操作しているので
> 外部から受けっとったGameObjectに含まれるLightコンポートネントの操作のみするようにして下さい。
> 
> 今、編集中なのでお待ちを

2020-11-14 10:24 UTC, rainierrr reviewed
レビューしました。

2020-11-14 10:24 UTC, rainierrr commented on Assets/button.cs
> +
今の状態だとシーンのすべてのライトが消えてしまうと思うので、ゲームオブジェクトを受け取って、そこに所属するライトコンポーネントのみを操作してほしいです。

あと初期状態を外部から設定できるように、Ture or Falseの値を外から受け取って(Unityのエディタ上で指定)、start関数のなかでライトのオンオフの状態を受け取って下さい。

参考：http://prince9.hatenablog.com/entry/2018/11/19/184813

2020-11-29 06:39 UTC, chicchi8 commented
遅くなってすみませんでした。
修正しました、よろしくお願いします。

## 修正内容
・シーンを分けた
・プレハブ化
・スクリプト修正

2020-12-05 09:35 UTC, rainierrr reviewed
修正ありがとうございます！

もう一度修正をお願いしたいです。
## 修正内容
###全体
PrefabフォルダにCanvasがありますがSenceにあるやつがプレハブから生成されてないので
プレハブから生成するようにお願いします。
PointLight (1)がなぜか最初はついてないので最初からつけておいてもいいと思いました。
OnOff.csをアタッチするのはButtonでいいと思います。(Scriptプレハブは削除で)

### 削除
使わないbutton.csとPoint Lightプレハブの削除
OnOffシーンで実装されている内容をLightSimulationシーンに実装（OnOffシーンは削除）

### 名前変更
Canvasの名前をUIに変更
ChangeLightプレハブの名前をLightGroup1に変更
Buttonの名前をLightButtonに変更
Buttonのテキスト（表示文字）をLight On/Offに変更
OnOff.csをLightOnOff.csに変更

前回指摘もれがありました。すいません。

2020-12-05 09:43 UTC, rainierrr commented on Assets/Scripts/OnOff/OnOff.cs
> +        }
こうかくとLightOn変数が消えたりしてスマートだと思います。
```
        if (ChangeLight.activeSelf) {
            ChangeLight.SetActive(false);
        }
        else {
            ChangeLight.SetActive(true);
        }
```

2020-12-05 09:43 UTC, rainierrr commented on Packages/packages-lock.json
> +        "com.unity.test-framework": "1.1.3"
1.1.3に変更されてしまっているので1.1.1に戻して下さい
ただしUnityを再起動すると再び1.1.3に変更されることがあるそうなのでその時は伝えて下さい
https://forum.unity.com/threads/packages-lock-json.912602/

2020-12-05 09:43 UTC, rainierrr commented on Assets/Scripts/OnOff/OnOff.cs
> +    private bool LightOn;
[SerializeField] privateではなく普通にpublicでいいと思います。
LightOn変数はいらなくなりますね。
https://qiita.com/makopo/items/8ef280b00f1cc18aec91

2021-01-07 15:07 UTC, chicchi8 commented
修正遅くなってすみませんでした。

## 修正内容
・プレハブからオブジェクトを生成
・指定されたシーンとプレハブの削除
・名前の変更
・スクリプトの改良
（上記修正内容を実装しました。）
## 修正できなかった内容
Packages/packages-lock.jsonの1.1.3を1.1.1に戻しても、Unityを再起動すると1.1.3に戻ってしまいます。

2021-01-08 11:14 UTC, rainierrr approved these changes
OKです！！！！！
お疲れ様でした

2021-01-08 11:14 UTC, merged